##监听端口
server:
  port: 8081

##数据源配置
spring:
#  profiles:
#    active: dev
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${DB_URL:jdbc:oracle:thin:@120.77.183.31:1521:xe}
    username: ${DB_USERNAME:CNOOC_JNJP}
    password: ${DB_PASSWORD:cnooc}
