##监听端口
server:
  port: 8081

##数据源配置
spring:
#  profiles:
#    active: release
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521:xe}
    url: ${DB_URL:jdbc:mysql://47.93.185.147:3306/dragon}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Aa_12345}

# Mybatis配置
mybatis-plus:
  mapper-locations: classpath:/static/mybatis/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.dragon.githubspringcloud.entity