##监听端口
server:
  port: 8081

##数据源配置
spring:
#  profiles:
#    active: dev
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${DB_USERNAME:C##dragon}
    password: ${DB_PASSWORD:dragon}
